// Core data shapes — mirrors the Mac app's ChatMessage/Conversation/Project
// structs so persisted state means the same things everywhere Eaon runs.
// Persisted as one state.json blob (see persistence.ts); every field added
// after first release must be optional so old data always decodes.

export type Role = "user" | "assistant";

export type AttachmentKind = "image" | "file";

/** A file/image attached to a message. The bytes live in the app data dir's
 *  attachments/ folder under `storedFileName`; the message only carries this
 *  reference so conversation JSON never grows megabytes of base64. */
export interface MessageAttachment {
  id: string;
  fileName: string;
  kind: AttachmentKind;
  storedFileName: string;
  /** Mime of the stored bytes (images are normalized to PNG on import). */
  mimeType: string;
}

/** One element of an OpenAI content-parts array — the vision wire shape. */
export type ContentPart =
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: { url: string } };

export interface ChatMessage {
  id: string;
  role: Role;
  content: string;
  /** Reasoning-model chain-of-thought, streamed separately from content. */
  reasoning: string;
  isError?: boolean;
  modelId?: string;
  modelDisplay?: string;
  timestamp: number;
  generationStartTime?: number;
  generationEndTime?: number;
  generatedTokenCount?: number;
  /** Set when this user message was sent via a "/name" skill invocation. */
  invokedSkillName?: string;
  /** An automated Agent tool-results message (run output, edits) — rendered
   *  as a compact collapsed card, not as normal prose. */
  isToolResult?: boolean;
  /** Files/images attached to this (user) message. */
  attachments?: MessageAttachment[];
  /** True when an attachment on this assistant message was generated by an
   *  image model (rendered large, no thumbnail chrome). */
  isGeneratedImage?: boolean;
}

export interface Conversation {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
  hasUnread?: boolean;
  projectId?: string | null;
  isPinned?: boolean;
}

export interface Project {
  id: string;
  name: string;
  createdAt: number;
}

/** A durable fact/event Eaon remembers about the user and brings into
 *  future chats — learned on-device, never leaves this PC except inside
 *  the requests it decorates. */
export interface Memory {
  id: string;
  text: string;
  kind: "fact" | "event";
  createdAt: number;
}

/** Which wire format a BYOK connection speaks. */
export type ProviderFormat = "openai" | "anthropic" | "gemini";

/** A BYOK connection. */
export interface CustomProvider {
  id: string;
  displayName: string;
  baseURL: string;
  apiKey: string;
  /** User-entered model ids this connection serves. */
  modelIDs: string[];
  /** Wire format — legacy state (no field) migrates to "openai". */
  format: ProviderFormat;
}

/** One configured MCP server — a remote Streamable-HTTP service (URL +
 *  pasted token) or a local stdio process (command + args). */
export interface McpServer {
  id: string;
  name: string;
  transport: "http" | "stdio";
  url: string;
  /** Authorization scheme word — "Bearer" for nearly everyone; Sentry and
   *  Semrush genuinely differ. */
  authScheme: string;
  token: string;
  command: string;
  /** Space-separated in the UI, split for spawn. */
  args: string;
  /** Disabled servers stay configured but are never connected. */
  enabled: boolean;
}

/** One tool a connected MCP server offers (name + JSON Schema). */
export interface McpToolInfo {
  name: string;
  description: string | null;
  inputSchema: Record<string, unknown>;
}

/** Persisted credentials for one catalog (built-in) MCP server — the
 *  cross-platform counterpart of the Mac app's per-service UserDefaults
 *  entry (`APIKeyStore`/`MCPOAuthCredentialStore`). Keyed by
 *  `MCP_CATALOG` entry id; absent from this array means never connected. */
export interface BuiltinMcpConnection {
  /** Matches an `McpCatalogEntry.id` in core/mcpCatalog.ts. */
  id: string;
  /** `authMode: "pastedToken"` — the raw token. */
  token?: string;
  /** `authMode: "oauth"` — Dynamic-Client-Registration-issued (or manually
   *  entered) client credentials, reused for every future sign-in. */
  clientId?: string;
  clientSecret?: string;
  /** `authMode: "oauth"` — the current access/refresh tokens. */
  accessToken?: string;
  refreshToken?: string;
  /** Milliseconds since epoch. */
  expiresAt?: number;
}

/** Which wire shape an image connection speaks.
 *  "openai": a cloud /images/generations API (DALL-E, gpt-image, or any
 *  compatible provider). "automatic1111": a local Stable Diffusion server
 *  (A1111 WebUI, DrawThings, ComfyUI in compatibility mode). */
export type ImageWireFormat = "openai" | "automatic1111";

/** One image-generation connection. */
export interface ImageProvider {
  id: string;
  displayName: string;
  baseURL: string;
  format: ImageWireFormat;
  apiKey: string;
  /** Model ids for "openai"; for "automatic1111" whatever's loaded in the
   *  local tool runs, so this is just a display label. */
  modelIDs: string[];
}

export type ThemeChoice = "Light" | "Dark" | "System";
export type FontSizeChoice = "Small" | "Medium" | "Large";
export type EaonMode = "chat" | "agent";

/** The Free Week trial credential minted for this device — hosted-model
 *  access without an account. A user-entered API key always wins over it. */
export interface TrialCredential {
  key: string;
  secret: string;
  expiresAt: number;
}

/** Where an installed skill came from — display-only, never affects behavior. */
export type SkillSource =
  | { kind: "starter" }
  | { kind: "localImport"; path: string }
  | { kind: "github"; url: string }
  | { kind: "manual" };

/** One installed skill — mirrors Claude Code's own SKILL.md shape (a name, a
 *  one-line description, and an instruction body), invoked with `/name`. */
export interface Skill {
  id: string;
  /** Lowercase, hyphenated — what the user types after `/`. */
  name: string;
  summary: string;
  instructions: string;
  source: SkillSource;
  /** Disabled skills stay installed but are invisible to `/` autocomplete. */
  isEnabled: boolean;
  installedAt: number;
}

/** Global sampling parameters — each independently opt-in; an off toggle
 *  means the field is NOT sent at all, which is not the same as sending a
 *  neutral value (reasoning models reject temperature outright). */
export interface ModelParams {
  temperatureEnabled: boolean;
  temperature: number;
  topPEnabled: boolean;
  topP: number;
  maxTokensEnabled: boolean;
  maxTokens: number;
  frequencyPenaltyEnabled: boolean;
  frequencyPenalty: number;
  presencePenaltyEnabled: boolean;
  presencePenalty: number;
}

export interface Settings {
  theme: ThemeChoice;
  fontSize: FontSizeChoice;
  accentColorId: string;
  /** UI font id from FONT_OPTIONS ("space-grotesk" default). */
  fontId: string;
  coloredUserBubble: boolean;
  showTokenSpeed: boolean;
  /** Check for a newer Eaon on startup and periodically. On by default;
   *  "Check for Updates" in General always works regardless of this. */
  autoUpdateEnabled: boolean;
  customInstructions: string;
  /** Key for Eaon's hosted models (was `aquaApiKey` before schema v2). */
  eaonApiKey: string;
  /** Free Week trial credential, if one was minted on this device. */
  trialCredential: TrialCredential | null;
  customProviders: CustomProvider[];
  ollamaBaseUrl: string;
  webSearchEnabled: boolean;
  alwaysAllowTools: boolean;
  /** Folds the wider device tools (trash/open app/URL) into Agent mode.
   *  Off by default. */
  deviceControlEnabled: boolean;
  /** Agent mode's open project folder (Cursor's "open folder"): the agent
   *  works inside it, relative tool paths resolve against it, and it's the
   *  default run_shell working directory. Null = no folder open; the agent
   *  then picks/creates one under home as before. */
  agentWorkspace: string | null;
  proxyEnabled: boolean;
  /** Optional outbound HTTP(S) proxy, e.g. "http://127.0.0.1:8080". */
  proxyUrl: string;
  hasSeenOnboarding: boolean;
  favorites: string[];
  nicknames: Record<string, string>;
  hiddenModelKeys: string[];
  /** Provider connections toggled off — hides all their models from the
   *  picker without deleting the connection or its saved key. Keys:
   *  "eaon", "ollama", or a CustomProvider's own id. */
  disabledProviders: string[];
  skills: Skill[];
  /** Facts Eaon has learned about the user, injected into future chats. */
  memories: Memory[];
  /** Whether Eaon auto-learns durable facts from conversations. */
  memoryEnabled: boolean;
  /** One-time cleanup flag for memories extracted before the junk gate
   *  existed (mirrors the Mac store's versioned junk-prune flag) — once
   *  true, the load-time prune never runs again, so entries the user adds
   *  by hand afterward are never touched. */
  memoryJunkPruneDone: boolean;
  /** Configured image-generation connections (cloud or local SD server). */
  imageProviders: ImageProvider[];
  /** Whether chat models may generate images via the eaon:image tool. */
  imageToolEnabled: boolean;
  modelParams: ModelParams;
  /** Configured MCP plugin servers (custom, user-added by URL). */
  mcpServers: McpServer[];
  /** Credentials for the built-in, individually-verified catalog servers
   *  (Settings → Plugins) — see core/mcpCatalog.ts. */
  builtinMcpConnections: BuiltinMcpConnection[];
  /** Off by default — turning this on opens a real listening network port. */
  localServerEnabled: boolean;
  /** 1234 by default — matches LM Studio's own local-server port. */
  localServerPort: number;
  localServerRequireApiKey: boolean;
  localServerApiKey: string;
}

export interface Statistics {
  promptsSent: number;
  charsGenerated: number;
  perModel: Record<string, { prompts: number; chars: number }>;
}

/** The whole persisted blob — schemaVersion 2 is this app; a blob without
 *  one is the 2026.3.x legacy shape and goes through migrateLegacyState. */
export interface AppStateBlob {
  schemaVersion: 2;
  conversations: Conversation[];
  projects: Project[];
  currentId: string | null;
  settings: Settings;
  statistics: Statistics;
}

// ---------------------------------------------------------------------------
// Runtime-only shapes (never persisted)
// ---------------------------------------------------------------------------

export interface OllamaModel {
  name: string;
  sizeBytes: number;
  paramSize?: string | null;
  quantization?: string | null;
  family?: string | null;
  /** Ollama's real capability tags ("completion", "vision", "image",
   *  "thinking", …). */
  capabilities?: string[] | null;
}

export interface ProviderModel {
  id: string;
  name?: string | null;
  modelType?: string | null;
  tier?: string | null;
}

/** A selectable chat model with its serving connection resolved.
 *  Picker keys: "eaon:<id>", "freeTrial:<id>", "ollama:<tag>", "custom:<configId>:<modelId>". */
export interface ModelEntry {
  key: string;
  /** The id sent in the request "model" field. */
  requestId: string;
  display: string;
  provider:
    | { kind: "eaon" }
    /** Same hosted catalog as "eaon", routed through the Free Week trial
     *  credential instead of the user's own key — its own provider, always
     *  selectable regardless of whether an Eaon API key is set. */
    | { kind: "freeTrial" }
    | { kind: "ollama" }
    | { kind: "custom"; configId: string; configName: string };
  tier?: string | null;
  supportsVision?: boolean;
}

export type SidebarSelection =
  | { kind: "chat" }
  | { kind: "projects" }
  | { kind: "models" }
  | { kind: "project"; id: string };

export interface PullState {
  status: string;
  completed: number;
  total: number;
  error?: string;
}

export interface SystemSpecs {
  totalMemBytes: number;
  cpuCores: number;
  os: string;
  arch: string;
}

/** Hardware-fit verdict for a model download, from RAM math alone. */
export type FitVerdict = "fits" | "tight" | "too-big" | "unknown";
