// /init — a light, honest project scan (top-level listing + manifest
// detection), written to EAON.md. Direct fs writes, not through the guarded
// write_file tool: this is a user-invoked CLI action, not a model tool call,
// so it doesn't need confirmation the way an agent-initiated write does.

import fs from "node:fs";
import path from "node:path";

const MANIFEST_HINTS: Array<{ file: string; label: string }> = [
  { file: "package.json", label: "Node.js" },
  { file: "Cargo.toml", label: "Rust" },
  { file: "go.mod", label: "Go" },
  { file: "pyproject.toml", label: "Python (pyproject)" },
  { file: "requirements.txt", label: "Python (pip)" },
  { file: "Gemfile", label: "Ruby" },
  { file: "composer.json", label: "PHP" },
  { file: "pom.xml", label: "Java (Maven)" },
  { file: "build.gradle", label: "Java/Kotlin (Gradle)" },
  { file: "Package.swift", label: "Swift" },
];

export const PROJECT_NOTES_FILE = "EAON.md";

export function readProjectNotes(projectRoot: string): string | null {
  try {
    return fs.readFileSync(path.join(projectRoot, PROJECT_NOTES_FILE), "utf8");
  } catch {
    return null;
  }
}

export async function runInit(projectRoot: string): Promise<{ file: string; summary: string }> {
  const entries = fs.readdirSync(projectRoot, { withFileTypes: true });
  const visible = entries.filter((e) => !e.name.startsWith("."));
  const dirs = visible.filter((e) => e.isDirectory()).map((e) => e.name).sort();
  const files = visible.filter((e) => e.isFile()).map((e) => e.name).sort();

  const detected = MANIFEST_HINTS.filter((m) => files.includes(m.file));

  let packageInfo = "";
  const pkgPath = path.join(projectRoot, "package.json");
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
      const bits: string[] = [];
      if (pkg.name) bits.push(`name: ${pkg.name}`);
      if (pkg.description) bits.push(`description: ${pkg.description}`);
      if (pkg.scripts) bits.push(`scripts: ${Object.keys(pkg.scripts).join(", ")}`);
      if (bits.length > 0) packageInfo = "\n\npackage.json — " + bits.join(" · ");
    } catch {
      // malformed package.json isn't worth failing /init over
    }
  }

  const lines = [
    `# EAON.md`,
    ``,
    `Auto-generated by \`/init\` on ${new Date().toISOString().slice(0, 10)}. Eaon reads this file automatically and includes it in its system prompt for this project — edit it freely to correct or extend what it knows.`,
    ``,
    `## Stack`,
    detected.length > 0 ? detected.map((d) => `- ${d.label} (${d.file})`).join("\n") : "- Not auto-detected — describe it here.",
    packageInfo,
    ``,
    `## Top-level layout`,
    dirs.length > 0 ? dirs.map((d) => `- ${d}/`).join("\n") : "(no subdirectories)",
    files.length > 0 ? files.slice(0, 40).map((f) => `- ${f}`).join("\n") : "",
    ``,
    `## Notes`,
    `Add build/test/run commands, conventions, or anything else worth Eaon knowing here.`,
    ``,
  ];
  const content = lines.join("\n");
  const target = path.join(projectRoot, PROJECT_NOTES_FILE);
  fs.writeFileSync(target, content, "utf8");
  return { file: target, summary: `Detected: ${detected.length > 0 ? detected.map((d) => d.label).join(", ") : "no recognized manifest"}. ${dirs.length} folders, ${files.length} files at the top level.` };
}
